name = "datahop"
[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
go_version = "1.18"
#module_path = "github.com/your/module/name"
#exec_pkg = "."

[builders."exec:go"]
enabled = true
#module_path = "github.com/your/module/name"

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name= "ping"
instances = { min = 1, max = 1000, default = 2 }

  [testcases.params]
#  secure_channel    = { type = "enum", desc = "secure channel used", values = ["noise", "tls"], default = "noise" }
  max_latency_ms    = { type = "int", desc = "maximum value for random local link latency", unit = "ms", default = 100 }
  iterations        = { type = "int", desc = "number of ping iterations we'll run against each peer", unit = "count", default = 5 }

# Add more testcases here...
# [[testcases]]
# name = "another"
# instances = { min = 1, max = 1, default = 1 }
#   [testcase.params]
#   param1 = { type = "int", desc = "an integer", unit = "units", default = 3 }
